### ISSUE TITLE
The App does not show dashboard items after rotation

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/dhis2-android-dashboard#74]

**Comment by manuelplazaspalacio** [comment]
I can't solve this. I solved the rotation problem but them appear an other crash when going to the previous page of the view pager. The bug is related to this question in stackoverflow:  https://stackoverflow.com/questions/19393076/how-to-properly-handle-screen-rotation-with-a-viewpager-and-nested-fragments
